name: test-Matrix

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node-version:
          - 16
          - 18
        exclude:
          - os: windows-latest
            node-version: 18
          - os: ubuntu-latest
            node-version: 16

    steps:
      - name: Enable Git long paths
        if: runner.os == 'Windows'
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
